"""Site-only Scripture detection, immutable scan ledger and editorial overrides.

The source fragment is never reserialized: wrappers are inserted at raw source
positions. Removing them recovers the exact original fragment, including entities.
"""
from __future__ import annotations
import hashlib
import html
from html.parser import HTMLParser
import json
import inspect
from pathlib import Path
import re
import subprocess
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = 1
DETECTOR = 'openbible-4.0.0/remnant-1'
MAX_MANIFEST = 32 * 1024 * 1024
QUERY = re.compile(r'(?:[1-9]|[1-5][0-9]|6[0-6]) [1-9][0-9]{0,2}:[1-9][0-9]{0,2}(?:-[1-9][0-9]{0,2})?\Z')
BLOCKS = set('p h1 h2 h3 h4 h5 h6 li td th figcaption blockquote div section article ul ol table tr br hr'.split())
ELIGIBLE = set('p h1 h2 h3 h4 h5 h6 li td th figcaption blockquote'.split())
SKIP = set('a button code pre script style noscript textarea select svg math nav aside'.split())
VOID = set('area base br col embed hr img input link meta param source track wbr'.split())


def strip_markers(source):
    """Remove only exact, text-only wrappers generated by this module."""
    return re.sub(r'<span class="scripture-reference" data-reference="[^"]+" data-scripture-id="[a-f0-9]{24}" data-translation="[a-z0-9]+">([^<]*)</span>', r'\1', source)


def canonical(value):
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(',', ':'))


def digest(value):
    return hashlib.sha256(value.encode('utf-8')).hexdigest()


def detector_version():
    files = [ROOT/'scripts/scan_scripture.mjs', *sorted((ROOT/'scripts/vendor/bcv').glob('*.js'))]
    return DETECTOR + '/' + digest(''.join(p.read_text() for p in files)+inspect.getsource(TextRuns)+inspect.getsource(source_spans)+canonical([sorted(BLOCKS),sorted(ELIGIBLE),sorted(SKIP),sorted(VOID)]))[:16]


class TextRuns(HTMLParser):
    """Decoded eligible runs with a character-to-original-source span map."""
    def __init__(self, source):
        super().__init__(convert_charrefs=False)
        self.source = source
        self.lines = [0]
        self.lines.extend(m.end() for m in re.finditer('\n', source))
        self.stack, self.runs, self.chars, self.spans = [], [], [], []
        self.feed(source)
        self.flush()

    def position(self):
        line, column = self.getpos()
        return self.lines[line-1] + column

    def flush(self):
        if self.chars:
            self.runs.append({'text': ''.join(self.chars), 'spans': self.spans})
        self.chars, self.spans = [], []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        skip = tag in SKIP or any(a.startswith('data-translation-notice') for a in attrs) or 'scripture-reference' in attrs.get('class', '').split() or attrs.get('aria-hidden') == 'true'
        if tag in BLOCKS or skip:
            self.flush()
        if tag not in VOID:
            self.stack.append((tag, skip))

    def handle_startendtag(self, tag, attrs):
        self.handle_starttag(tag, attrs)
        if tag not in VOID:
            self.handle_endtag(tag)

    def handle_endtag(self, tag):
        if tag in BLOCKS or tag in SKIP:
            self.flush()
        for i in range(len(self.stack)-1, -1, -1):
            if self.stack[i][0] == tag:
                if any(skip for _, skip in self.stack[i:]):
                    self.flush()
                del self.stack[i:]
                break

    def allowed(self):
        return any(t in ELIGIBLE for t, _ in self.stack) and not any(skip for _, skip in self.stack)

    def handle_data(self, data):
        if self.allowed():
            offset = self.position()
            self.chars.extend(data)
            self.spans.extend((offset+i, offset+i+1) for i in range(len(data)))

    def entity(self, text):
        if self.allowed():
            decoded = html.unescape(text)
            offset = self.position()
            self.chars.extend(decoded)
            self.spans.extend([(offset, offset+len(text))] * len(decoded))

    def handle_entityref(self, name):
        self.entity('&'+name+(';' if self.source[self.position()+len(name)+1:self.position()+len(name)+2] == ';' else ''))

    def handle_charref(self, name):
        self.entity('&#'+name+(';' if self.source[self.position()+len(name)+2:self.position()+len(name)+3] == ';' else ''))


def source_spans(run, start, end):
    spans = []
    for left, right in run['spans'][start:end]:
        if spans and left <= spans[-1][1]:
            spans[-1][1] = max(right, spans[-1][1])
        else:
            spans.append([left, right])
    return spans


def anchor(run, start, end):
    return {'quote': run['text'][start:end], 'before': run['text'][max(0,start-40):start], 'after': run['text'][end:end+40]}


def locate(runs, value):
    matches = []
    quote = value.get('quote', '')
    if not quote:
        return matches
    for run in runs:
        start = 0
        while (start := run['text'].find(quote, start)) >= 0:
            end = start+len(quote)
            if (not value.get('before') or run['text'][:start].endswith(value['before'])) and (not value.get('after') or run['text'][end:].startswith(value['after'])):
                matches.append((run, start, end))
            start += 1
    return matches


def valid_record(key, record):
    if not isinstance(record, dict) or set(record) != {'article_id','locale','content_hash','detector','markers','record_hash'}:
        return False
    if not re.fullmatch(r'[a-f0-9-]{36}',str(record['article_id'])) or not re.fullmatch(r'[A-Za-z-]{2,7}',str(record['locale'])) or not re.fullmatch(r'[a-f0-9]{64}',str(record['content_hash'])) or not isinstance(record['detector'],str):
        return False
    if not isinstance(record['markers'],list) or len(record['markers']) > 10000:
        return False
    for marker in record['markers']:
        if not isinstance(marker,dict) or set(marker) != {'id','quote','before','after','spans','osis','queries'}:
            return False
        if not re.fullmatch(r'[a-f0-9]{24}',str(marker['id'])) or not all(isinstance(marker[k],str) for k in ('quote','before','after','osis')):
            return False
        if not marker['quote'] or len(marker['quote']) > 2000 or len(marker['before']) > 40 or len(marker['after']) > 40:
            return False
        if not isinstance(marker['queries'],list) or not 1 <= len(marker['queries']) <= 12 or not all(isinstance(q,str) and QUERY.fullmatch(q) for q in marker['queries']):
            return False
        if not isinstance(marker['spans'],list) or not marker['spans'] or any(not isinstance(span,list) or len(span) != 2 or any(type(n) != int for n in span) or not 0 <= span[0] < span[1] for span in marker['spans']):
            return False
    expected = ':'.join(str(record.get(x,'')) for x in ('article_id','locale','content_hash','detector'))
    return key == expected and record.get('record_hash') == digest(canonical({k:v for k,v in record.items() if k != 'record_hash'}))


def load_manifest(path):
    if path.is_dir():
        combined = {}
        for shard in sorted(path.glob('[0-9a-f].json')):
            combined.update(load_manifest(shard))
        return combined
    if not path.is_file():
        return {}
    if path.stat().st_size > MAX_MANIFEST:
        raise ValueError('Scripture ledger exceeds size limit')
    value = json.loads(path.read_text())
    if set(value) != {'schema_version','integrity','records'} or value.get('schema_version') != SCHEMA or not isinstance(value.get('records'), dict):
        raise ValueError('Invalid Scripture ledger schema')
    if value.get('integrity') != digest(canonical(value['records'])):
        raise ValueError('Scripture ledger integrity mismatch')
    if not all(valid_record(k,v) for k,v in value['records'].items()):
        raise ValueError('Invalid Scripture scan record')
    return value['records']


def save_manifest(path, records):
    path.parent.mkdir(parents=True, exist_ok=True)
    value = {'schema_version':SCHEMA, 'integrity':digest(canonical(records)), 'records':dict(sorted(records.items()))}
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2)+'\n')


class Scripture:
    def __init__(self, *, ledger=None, cache=None, overrides=None, translations=None):
        self.version = detector_version()
        self.records = {}
        for path in (ledger or ROOT/'data/scripture-ledger', cache or ROOT/'.build/scripture-manifest.json'):
            try:
                self.records.update(load_manifest(Path(path)))
            except (ValueError, json.JSONDecodeError) as error:
                raise ValueError(f'Cannot reuse Scripture ledger {path}: {error}') from error
        self.overrides = json.loads((overrides or ROOT/'data/scripture-overrides.json').read_text())
        if self.overrides.get('schema_version') != SCHEMA or not isinstance(self.overrides.get('articles'), dict):
            raise ValueError('Invalid Scripture override schema')
        self.translations = json.loads((translations or ROOT/'data/scripture-translations.json').read_text())['locales']
        self.current, self.report = {}, {'scanned':0, 'reused':0, 'detected':0, 'rendered':0, 'suppressed':0, 'unavailable':0, 'review_required':[]}

    def key(self, locale, article):
        return ':'.join((article['id'],locale,digest(article['html']),self.version))

    def prepare(self, articles):
        pending, batch = [], []
        for locale, items in articles.items():
            for article in items:
                key = self.key(locale, article)
                if key in self.records:
                    self.current[(locale, article['id'])] = self.records[key]
                    self.report['reused'] += 1
                    continue
                runs = TextRuns(article['html']).runs
                pending.append((key,locale,article,runs,len(batch)))
                batch.extend({'locale':locale,'text':run['text']} for run in runs)
        results = []
        if batch:
            process = subprocess.run(['node', str(ROOT/'scripts/scan_scripture.mjs')], input=json.dumps(batch, ensure_ascii=False), text=True, capture_output=True, timeout=600)
            if process.returncode:
                raise RuntimeError('Scripture detector failed; run npm ci first. '+process.stderr[-3000:])
            results = json.loads(process.stdout)
            if len(results) != len(batch):
                raise ValueError('Incomplete Scripture detector result')
        for key,locale,article,runs,offset in pending:
            markers = []
            for run, detected in zip(runs,results[offset:offset+len(runs)]):
                for found in detected:
                    start,end = found['start'],found['end']
                    value = anchor(run,start,end)
                    spans = source_spans(run,start,end)
                    marker_id = digest(canonical([article['id'],locale,value,spans]))[:24]
                    markers.append({'id':marker_id, **value, 'spans':spans, 'osis':found['osis'], 'queries':found['queries']})
            record = {'article_id':article['id'],'locale':locale,'content_hash':digest(article['html']),'detector':self.version,'markers':markers}
            record['record_hash'] = digest(canonical(record))
            self.records[key] = record
            self.current[(locale,article['id'])] = record
            self.report['scanned'] += 1
        self.report['detected'] = sum(len(record['markers']) for record in self.current.values())

    def render(self, locale, article):
        source = article['html']
        record = self.current.get((locale,article['id']))
        if record is None:
            self.prepare({locale:[article]})
            record = self.current[(locale,article['id'])]
        markers = [dict(marker) for marker in record['markers']]
        rules = self.overrides['articles'].get(locale+':'+article['id'], [])
        if not isinstance(rules,list) or any(not isinstance(rule,dict) for rule in rules):
            raise ValueError('Scripture article overrides must be a list of rules')
        runs = None
        withheld = False
        for rule in rules:
            if rule.get('action') not in {'suppress','include'} or not isinstance(rule.get('anchor'),dict):
                raise ValueError('Each Scripture override needs action and an anchor')
            if runs is None:
                runs = TextRuns(source).runs
            locations = locate(runs,rule['anchor'])
            targets = [m for m in markers if rule.get('marker_id') == m['id']]
            spans = None
            if len(locations) == 1:
                run,start,end = locations[0]
                spans = source_spans(run,start,end)
                # A newer detector may extend a previously rejected selection.
                # Suppression applies to overlapping matches, not exact spans only.
                targets += [m for m in markers if any(a < d and b > c for a,b in m['spans'] for c,d in spans)]
            if rule['action'] == 'suppress':
                if targets:
                    ids = {m['id'] for m in targets}
                    markers = [m for m in markers if m['id'] not in ids]
                    self.report['suppressed'] += len(ids)
                elif len(locations) != 1:
                    # Fail closed: an unresolved editorial rejection cannot return.
                    markers = []
                    withheld = True
                    self.report['review_required'].append({'locale':locale,'article_id':article['id'],'marker_id':rule.get('marker_id'),'reason':'suppression anchor missing or ambiguous; article enrichment withheld'})
            elif spans:
                queries = rule.get('queries',[])
                if not isinstance(queries,list) or not 1 <= len(queries) <= 12 or not all(isinstance(q,str) and QUERY.fullmatch(q) for q in queries):
                    raise ValueError('Include override has invalid canonical queries')
                marker_id = rule.get('marker_id') or digest(canonical(rule))[:24]
                if not re.fullmatch(r'[a-f0-9]{24}',marker_id):
                    raise ValueError('Invalid editorial marker ID')
                replacement = {'id':marker_id,**anchor(run,start,end),'spans':spans,'osis':rule.get('osis',''),'queries':queries}
                ids = {m['id'] for m in targets}
                markers = [m for m in markers if m['id'] not in ids] + [replacement]
            else:
                self.report['review_required'].append({'locale':locale,'article_id':article['id'],'reason':'include anchor missing or ambiguous'})
        if withheld:
            markers = []
        translation = self.translations.get(locale,{}).get('abbreviation')
        if not translation:
            self.report['unavailable'] += len(markers)
            return source
        # Recheck cached spans against eligible source runs, without invoking the
        # detector. A public cache can never turn a notice/link/code into a marker.
        runs = runs if runs is not None else TextRuns(source).runs
        insertions, used = [], []
        for marker in markers:
            if not marker.get('queries') or not all(QUERY.fullmatch(q) for q in marker['queries']):
                raise ValueError('Unsafe Scripture query in saved record')
            spans = marker['spans']
            if not spans or any(not isinstance(a,int) or not isinstance(b,int) or not 0 <= a < b <= len(source) for a,b in spans):
                raise ValueError('Invalid Scripture source spans')
            if not any(source_spans(run,start,end) == spans for run,start,end in locate(runs,marker)):
                raise ValueError('Saved Scripture marker is outside eligible source text')
            if ''.join(html.unescape(source[a:b]) for a,b in spans) != marker['quote']:
                raise ValueError('Saved Scripture quotation does not match source')
            if any('<' in source[a:b] for a,b in spans):
                raise ValueError('Saved Scripture span crosses markup')
            if any(a < d and b > c for a,b in spans for c,d in used):
                raise ValueError('Overlapping Scripture markers')
            used.extend(spans)
            for index,(a,b) in enumerate(spans):
                attrs = {'class':'scripture-reference','data-reference':';'.join(marker['queries']),'data-scripture-id':marker['id'],'data-translation':translation}
                opening = '<span '+ ' '.join(k+'="'+html.escape(str(v),quote=True)+'"' for k,v in attrs.items())+'>'
                insertions.extend([(a,opening),(b,'</span>')])
            self.report['rendered'] += 1
        for position,value in sorted(insertions,key=lambda item:item[0],reverse=True):
            source = source[:position]+value+source[position:]
        if insertions and strip_markers(source) != article['html']:
            raise ValueError('Scripture wrapping changed source HTML')
        return source

    def save(self, output):
        # The published snapshot contains only current articles/revisions. Old
        # immutable records may remain in Git history, never in current output.
        active = {':'.join(record[k] for k in ('article_id','locale','content_hash','detector')):record for record in self.current.values()}
        save_manifest(output/'scripture/manifest.json',active)
        save_manifest(ROOT/'.build/scripture-manifest.json',active)
        (ROOT/'.build/scripture-report.json').write_text(json.dumps(self.report,ensure_ascii=False,indent=2)+'\n')


def fetch_published(destination):
    """Fixed origin, bounded read, no redirects; unavailable first publication is OK."""
    class NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self,*args):
            return None
    try:
        with urllib.request.build_opener(NoRedirect).open('https://remnant.truechristian.church/scripture/manifest.json', timeout=30) as response:
            raw = response.read(MAX_MANIFEST+1)
        if len(raw) > MAX_MANIFEST:
            raise ValueError('Published Scripture ledger too large')
        destination.parent.mkdir(parents=True,exist_ok=True)
        temporary = destination.with_suffix('.incoming.json')
        temporary.write_bytes(raw)
        try:
            load_manifest(temporary)
            temporary.replace(destination)
        finally:
            temporary.unlink(missing_ok=True)
        print('Reused published Scripture manifest')
    except Exception as error:
        print(f'Published Scripture manifest unavailable; using reviewed/local ledger: {type(error).__name__}: {error}')


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--fetch-published',action='store_true')
    args=parser.parse_args()
    if args.fetch_published:
        fetch_published(ROOT/'.build/scripture-manifest.json')
